---
- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - common

- hosts: controlplane
  gather_facts: yes
  become: yes
  roles:
    - { role: controlplane, tags: controlplane }
    - { role: addons/cni, tags: cni }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: nodes, tags: nodes }
